/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * src/chatroom.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "http://localhost".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *  
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 * 
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 * 
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface ScalaServerPlaygroundChannelInfo
 */
export interface ScalaServerPlaygroundChannelInfo {
    /**
     * 
     * @type {string}
     * @memberof ScalaServerPlaygroundChannelInfo
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ScalaServerPlaygroundChannelInfo
     */
    uuid: string;
    /**
     * 
     * @type {Array&lt;ScalaServerPlaygroundUserInfo&gt;}
     * @memberof ScalaServerPlaygroundChannelInfo
     */
    users?: Array<ScalaServerPlaygroundUserInfo>;
}

/**
 * 
 * @export
 * @interface ScalaServerPlaygroundChatMessage
 */
export interface ScalaServerPlaygroundChatMessage {
    /**
     * 
     * @type {string}
     * @memberof ScalaServerPlaygroundChatMessage
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof ScalaServerPlaygroundChatMessage
     */
    userUuid: string;
    /**
     * 
     * @type {string}
     * @memberof ScalaServerPlaygroundChatMessage
     */
    channelUuid: string;
    /**
     * 
     * @type {string}
     * @memberof ScalaServerPlaygroundChatMessage
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof ScalaServerPlaygroundChatMessage
     */
    timestamp: string;
}

/**
 * 
 * @export
 * @interface ScalaServerPlaygroundCommand
 */
export interface ScalaServerPlaygroundCommand {
    /**
     * 
     * @type {string}
     * @memberof ScalaServerPlaygroundCommand
     */
    method: string;
    /**
     * 
     * @type {number}
     * @memberof ScalaServerPlaygroundCommand
     */
    seq: number;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof ScalaServerPlaygroundCommand
     */
    errors?: Array<string>;
}

/**
 * 
 * @export
 * @interface ScalaServerPlaygroundUserInfo
 */
export interface ScalaServerPlaygroundUserInfo {
    /**
     * 
     * @type {string}
     * @memberof ScalaServerPlaygroundUserInfo
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ScalaServerPlaygroundUserInfo
     */
    uuid: string;
}

/**
 * 
 * @export
 * @interface ServerAuthed
 */
export interface ServerAuthed {
    /**
     * 
     * @type {ScalaServerPlaygroundCommand}
     * @memberof ServerAuthed
     */
    cmd: ScalaServerPlaygroundCommand;
    /**
     * 
     * @type {ScalaServerPlaygroundUserInfo}
     * @memberof ServerAuthed
     */
    identity: ScalaServerPlaygroundUserInfo;
}

/**
 * 
 * @export
 * @interface ServerBaseRes
 */
export interface ServerBaseRes {
    /**
     * 
     * @type {ScalaServerPlaygroundCommand}
     * @memberof ServerBaseRes
     */
    cmd: ScalaServerPlaygroundCommand;
}

/**
 * 
 * @export
 * @interface ServerBroadcast
 */
export interface ServerBroadcast {
    /**
     * 
     * @type {ScalaServerPlaygroundCommand}
     * @memberof ServerBroadcast
     */
    cmd?: ScalaServerPlaygroundCommand;
    /**
     * 
     * @type {Array&lt;ScalaServerPlaygroundChannelInfo&gt;}
     * @memberof ServerBroadcast
     */
    channels: Array<ScalaServerPlaygroundChannelInfo>;
    /**
     * 
     * @type {Array&lt;ScalaServerPlaygroundChatMessage&gt;}
     * @memberof ServerBroadcast
     */
    messages: Array<ScalaServerPlaygroundChatMessage>;
}

/**
 * 
 * @export
 * @interface ServerJoinedChannel
 */
export interface ServerJoinedChannel {
    /**
     * 
     * @type {ScalaServerPlaygroundCommand}
     * @memberof ServerJoinedChannel
     */
    cmd: ScalaServerPlaygroundCommand;
    /**
     * 
     * @type {ScalaServerPlaygroundChannelInfo}
     * @memberof ServerJoinedChannel
     */
    channel: ScalaServerPlaygroundChannelInfo;
    /**
     * 
     * @type {Array&lt;ScalaServerPlaygroundChatMessage&gt;}
     * @memberof ServerJoinedChannel
     */
    history: Array<ScalaServerPlaygroundChatMessage>;
}

/**
 * 
 * @export
 * @interface ServerLeftChannel
 */
export interface ServerLeftChannel {
    /**
     * 
     * @type {ScalaServerPlaygroundCommand}
     * @memberof ServerLeftChannel
     */
    cmd: ScalaServerPlaygroundCommand;
    /**
     * 
     * @type {string}
     * @memberof ServerLeftChannel
     */
    reason: string;
}

/**
 * 
 * @export
 * @interface ServerPong
 */
export interface ServerPong {
    /**
     * 
     * @type {ScalaServerPlaygroundCommand}
     * @memberof ServerPong
     */
    cmd: ScalaServerPlaygroundCommand;
}

/**
 * 
 * @export
 * @interface ServerSentChat
 */
export interface ServerSentChat {
    /**
     * 
     * @type {ScalaServerPlaygroundCommand}
     * @memberof ServerSentChat
     */
    cmd: ScalaServerPlaygroundCommand;
    /**
     * 
     * @type {ScalaServerPlaygroundChatMessage}
     * @memberof ServerSentChat
     */
    msg: ScalaServerPlaygroundChatMessage;
}


