version: '2'

volumes:
  scala-server-pgsql-dev:
  scala-server-redis-dev:

services:
  pgsql:
    image: postgres:10.6-alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: secret
    volumes:
      - scala-server-pgsql-dev:/var/lib/postgresql/data
    ports:
      - 65432:5432
    restart: always

  redis:
    image: redis:5.0-alpine
    volumes:
      - scala-server-redis-dev:/var/lib/postgresql/data
    ports:
      - 59379:6379
    restart: always

  nginx-front:
    image: alpine:3.9
    network_mode: host
    volumes:
      - "../web/build:/web:ro"
      - "./certs:/certs:ro"
      - "./nginx-conf.d:/etc/nginx/conf.d:ro"
    command: |
      sh -c "apk add --update nginx ; mkdir -pv /run/nginx && ln -svf /dev/stdout /var/log/nginx/access.log && ln -svf /dev/stderr /var/log/nginx/error.log && exec nginx -g 'daemon off;'"
    restart: always
